language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
    allow_failures:
        - php: 7.2
        - php: 7.3
        - php: 8.0
        - php: nightly

addons:
  chrome: stable

env:
  global:
    - APP_ENV=local
    - APP_DEBUG=true
    - APP_KEY=base64:jNI+qJRj1eqN3RWMeBWo6sxMwKzgDP7Py2AfRJ1luyA=
    - APP_URL=http://127.0.0.1:8000
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=test
    - DB_USERNAME=root
    - DB_PASSWORD=
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync
    - REDIS_HOST=127.0.0.1
    - REDIS_PASSWORD=null
    - REDIS_PORT=6379
    - MAIL_DRIVER=smtp
    - MAIL_HOST=mailtrap.io
    - MAIL_PORT=2525
    - MAIL_USERNAME=null
    - MAIL_PASSWORD=null
    - MAIL_ENCRYPTION=null

sudo: false

services: mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot


install: 
    - cp .env.example .env
    - travis_retry composer install --no-interaction --prefer-source
    - php artisan key:generate
    - php artisan dusk:chrome-driver


before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &


script: vendor/bin/phpunit --coverage-clover=coverage.clover


after_script:
    - php artisan dusk
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
